# Generated by Django 5.1.2 on 2024-11-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0004_alter_watches_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='watches',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount applied to the item, if any.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='watches',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Indicates whether the item is available or not.'),
        ),
    ]
